info:
 name: HYSTRIX-TURBINE
 description: HYSTRIX-TURBINE
 version: 1.0.0
---
server:
  port: 9200
---
security:
  ignored: true
---
turbine:
  aggregator:
    clusterConfig: MYCLUSTER
  appConfig: microservice-one,microservice-two,zuul-server  # No spaces (see https://github.com/spring-cloud/spring-cloud-netflix/issues/948)
  clusterNameExpression: metadata['cluster']
  combineHostPort: true  # Necessary if you run two or more services in a single host
---
eureka:
  hostname: localhost
  password: s3cr3t
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

