info:
  name: Microservice-ONE
  description: Microservice-ONE
  version: 1.0
---
server:
  port: 9001
---
eureka:
  hostname: localhost
  password: s3cr3t
  instance:
    metadataMap:
      cluster: MYCLUSTER
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
# http://localhost:8500/v1/catalog/service/microservice-one?pretty=true
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # For the local environment to work ... (remove for real life)
        healthCheckUrl: "http://localhost:${server.port}/health"
        healthCheckInterval: 30s
        tags: cluster=MYCLUSTER,availability-zone-A
        serverListQueryTags: { microservice-two : availability-zone-A }
---
# https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    testCallTwo:
      execution:
        isolation.thread.timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 2    # For testing purposes
---
logging:
  level:
    org.springframework.cloud: DEBUG
    com.ecwid.consul: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-B3-TraceId:-},span=%X{X-B3-SpanId:-}] [%15.15t] %-40.40logger{39}: %m%n'
---
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
