info:
 name: zuul-server
 description: Zuul Server
 version: 1.0.0
---
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  enabled: true
  sensitive: false
---
server:
  port: 8080
---
eureka:
  hostname: localhost
  password: s3cr3t
  instance:
    metadataMap:
      cluster: MYCLUSTER
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # For the local environment to work ... (remove for real life)
        healthCheckUrl: http://localhost:${server.port}/health
        healthCheckInterval: 30s
        tags: cluster=MYCLUSTER
---
zuul:
 routes:
  microservice-one:  
   path: /microserviceOne/**
   serviceId: microservice-one
   strip-prefix: false
  microservice-two:  
   path: /microserviceTwo/**
   serviceId: microservice-two
   strip-prefix: false
---
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-B3-TraceId:-},span=%X{X-B3-SpanId:-}] [%15.15t] %-40.40logger{39}: %m%n'

