info:
  name: Microservice-TWO
  description: Microservice-TWO
  version: 1.0
---
server:
  port: 9002
  contextPath: /microservice-two
---
eureka:
  hostname: localhost
  password: s3cr3t
  instance:
    metadataMap:
      cluster: MYCLUSTER
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-B3-TraceId:-},span=%X{X-B3-SpanId:-}] [%15.15t] %-40.40logger{39}: %m%n'
---
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
