info:
  name: Eureka Server
  description: Eureka Server
  version: 1.0.0
---
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  enabled: true
  sensitive: false
---
server:
 port: 8761
---
eureka:
 dashboard:
  enabled: true
 instance:
  hostname: localhost
 client:
  healthcheck:
   enabled: true
  registerWithEureka: false
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 server:
  waitTimeInMsWhenSyncEmpty: 0
  renewalPercentThreshold: 0.49
