info:
  name: Microservice-TWO
  description: Microservice-TWO
  version: 1.0
---
server:
  port: 9002
---
eureka:
  hostname: localhost
  password: s3cr3t
  instance:
    metadataMap:
      cluster: MYCLUSTER
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
# http://localhost:8500/v1/catalog/service/microservice-two?pretty=true
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # For the local environment to work ... (remove for real life)
        healthCheckUrl: http://localhost:${server.port}/health
        healthCheckInterval: 30s
        tags: cluster=MYCLUSTER
---
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-B3-TraceId:-},span=%X{X-B3-SpanId:-}] [%15.15t] %-40.40logger{39}: %m%n'
---
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
